### ISSUE TITLE
Delays in generic input connections - not honoured by SpineML_2_BRAHMS - are they correct SpineML?

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/spineml#2]
Question for @ajc158 and @mondus Is a delay in a generic input connection correct SpineML? Is it covered by the validation scheme correctly?

**Comment by mondus** [comment]
Yes an Input uses the same connection elements as a projection so Delay is
specified in exactly the same way.

On 1 July 2016 at 15:38, Seb James notifications@github.com wrote:

> Question for @ajc158 https://github.com/ajc158 and @mondus
> https://github.com/mondus Is a delay in a generic input connection
> correct SpineML? Is it covered by the validation scheme correctly?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/SpineML/spineml/issues/2, or mute the thread
> https://github.com/notifications/unsubscribe/AKkJu6UkVR5vGuYIDZtQhm-I2rvDjQg9ks5qRSZ0gaJpZM4JDM6E
> .

## 

Dr Paul Richmond (Research Fellow) - University of Sheffield
http://www.paulrichmond.staff.shef.ac.uk
p.richmond@sheffield.ac.uk

Department of Computer Science http://www.sheffield.ac.uk/dcs
Sheffield NVIDIA CUDA Research Centre
http://gpucomputing.sites.sheffield.ac.uk/
Advanced Computing Research Centre http://www.acrc.com

**Comment by sebjameswml** [comment]
Ok, thanks Paul.
